name: Update Version
on: 
  push:
    branches:
      - main
    paths-ignore: 
      - 'package.json'
jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Bump version
        run: npm version patch