name: Update Version
on: 
  push:
    branches:
      - main

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    if: "startsWith(github.event.head_commit.message, '[RELEASE]')"
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
      - run: git config --global user.name 'LocomotiveHouse'
      - run: git config --global user.email 'noreply@locomotivehouse.com'
      - run: npm version patch -m "[RELEASE] %s"
      - run: git push